language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
jdk:
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk7
	- rvm: ruby-head
      jdk: oraclejdk7
