sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
jdk:
  - oraclejdk7
bundler_args: --retry 3
before_install:
  - travis_retry gem update --system
  - gem --version
  - gem update bundler
